apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rj0onnw12-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:12e2c88b715527e0a489732bf0667e0cb8934e8a@sha256:84f2764121b6db3bf3f7adce64dcad439a701ae92e65e0a1cff977e1a5833a8e
          name: container-image
